services:

  frontend:
    container_name: frontend-server
    build:
      context: ../../Part1/ex1.12/
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - frontnet

  backend:
    container_name: backend-server
    build:
      context: ../../Part1/ex1.13/
      dockerfile: Dockerfile
    expose:
      - "8081"
    environment:
      - REQUEST_ORIGIN=*
      - REDIS_HOST=redis-server
      - POSTGRES_HOST=db-server
      - POSTGRES_PASSWORD=Kissa123
    networks:
      - backnet
    depends_on:
      - db

  redis:
    container_name: redis-server
    image: redis:latest
    command: ["redis-server"]
    expose:
      - "6379"
    networks:
      - backnet

  db:
    container_name: db-server
    image: postgres:latest
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Kissa123
    expose:
      - "5432"
    restart: unless-stopped
    networks:
      - backnet

  proxy:
    container_name: proxy-server
    image: nginx:latest
    volumes:
      - /Users/zamir/Dropbox/Opiskelu/devops-with-docker/Part2/ex2.8/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "127.0.0.1:80:80/tcp"
    networks:
      - frontnet
      - backnet

volumes:
  database:

networks:
  frontnet:
    name: frontnet

  backnet:
    name: backnet

