services:

  frontend-server:
    container_name: frontend-server
    build:
      context: ./frontend/
      dockerfile: Dockerfile

  backend-server:
    container_name: backend-server
    build:
      context: ./backend/
      dockerfile: Dockerfile
    depends_on:
      - db-server
      - redis-server

  redis-server:
    container_name: redis-server
    image: redis:latest
    command: ["redis-server"]
    expose:
      - "6379"

  db-server:
    container_name: db-server
    image: postgres:latest
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Kissa123
    expose:
      - "5432"
    restart: unless-stopped

  proxy-server:
    container_name: proxy-server
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "127.0.0.1:80:80/tcp"
    depends_on:
      - frontend-server
      - backend-server

volumes:
  database:

